name: Publish

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Generate data
        run: ./gradlew runData
        env:
          VTS_VERSION: ${{ github.event.release.tag_name }}
      - name: Build
        run: ./gradlew build
        env:
          VTS_VERSION: ${{ github.event.release.tag_name }}
      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/villager-trading-station-${{ github.event.release.tag_name }}.jar
          tag_name: ${{ github.event.release.tag_name }}
      - name: Upload to external sites
        run: ./gradlew curseforge
        env:
          VTS_VERSION: ${{ github.event.release.tag_name }}
          CURSEFORGE: ${{ secrets.CURSEFORGE }}
